### PR TITLE
Fix persistence

### PR DESCRIPTION
**Pull request by dacleyra**
The former syntax was causing failures for others. I'm not quite sure if it's a difference in helm version behavior, or it was always failing.

Add the additional check for persistence.enabled so the PV is not created when persistence is disabled.

Jag needs to verify on minikube before blessing for acceptance.

### CODE REVIEW

**Comment by jagraj** [comment]
Hi ,

with this new chart, the behavior is changed. Vote service is started first then cloudant db started. we create key tables in cloudant database during container startup and they are missing for next vote call. This is failing for both default and persistence enabled installs.

**Comment by jagraj** [comment]
we do not want cloudant chart to be installed for default case. we want cloudant chart to be deployed if persistence=true

**Comment by dacleyra** [comment]
Cloudant will always be deployed, since it exists as a requirement sub-chart.
If the sub-chart had its own flag to toggle the deployment, then it could be controlled - but it does not. 
There is no other mechanism I'm aware of to prevent the sub-chart from being deployed.

**Comment by dacleyra** [comment]
dbUrl should have been based off of Release.Name, though this was not noticed/failing under MsB where Release.Name was being set to Chart.Name by the pipeline

Update the basedeployment for the app versioning scenario as well

**Pull request merged**
